version: '3.9'

services:
  idempiere:
    image: ${DOCKER_REPOSITORY}:${DOCKER_TAG}
    ports:
      - 8080:8080
      - 8443:8443
      - 12612:12612
    environment:
      - TZ=America/Guayaquil
    volumes:
      - idempiere_config:/opt/idempiere/configuration
      - idempiere_plugins:/opt/idempiere/plugins
    networks:
      idempiere_network:

  postgres:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - 5432:5432
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_PASSWORD=postgres
    volumes:
      - idempiere_data:/var/lib/postgresql/data
    networks:
      idempiere_network:

volumes:
  idempiere_data:
  idempiere_plugins:
  idempiere_config:

networks:
  idempiere_network: